### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by wumingyao** [yule-BUAA/DSTGCN#2]
您好，可以分享一下您的数据集吗

**Comment by qiaodaben** [comment]
> 您好，可以分享一下您的数据集吗

你收到作者回复了吗？

**Comment by yule-BUAA** [comment]
您好，
       感谢对这项工作的关注。由于部分原始数据有隐私问题，我们无法提供原始数据。但是为了使这项工作更便于跟进，我们在更新的版本中提供了原始数据预处理代码、数据格式说明以及预处理之后经采样的数据集。
      我们的模型可以在使用预处理后的数据集上直接进行运行并得到结果。希望能有所帮助。
祝好

**Comment by qiaodaben** [comment]
> 您好， 感谢对这项工作的关注。由于原始数据存在隐私问题，我们无法提供原始数据，但为了使该工作更易于跟踪，在版本中提供了我们更新的原始数据代码代码、数据格式说明以及之后经过的数据。 我们的模型可以在使用设置后的数据集上直接运行得到结果。希望能有帮助。 祝好。
你考虑将模型上传到北航提供的交通平台么libcity，这样方便后续的对比工作
