### ISSUE TITLE
edges_data.h5中spatial_features属性的处理问题

### ISSUE THREAD

**Issue by HaozheZhao** [yule-BUAA/DSTGCN#5]
您好，我对于数据处理当中有关spatial_features的处理有一定的问题，该部分内容并未在processing_data中涵盖，是否是项目上传时存在缺失，亦或是属于敏感数据并未公开？

**Comment by yule-BUAA** [comment]
您好，
        spatial_features这部分是由于POI数据是公司提供的，所以不便将提取关于POI的空间特征这部分相关的数据处理代码公开。我在这里描述下提取spatial_features的流程：
         1）对于路网结构信息，我们提供的预处理代码process_beijing_road_net.py可以生成beijing_roadnet.gpickle，该文件中的节点为每条道路，边为道路之间的连接关系，同时也包含了道路的2维属性信息（道路长度、道路包含的点数量）；
         2）对于POI信息，我们提取了每条道路周围的各类型POI的数量（在使用的数据中，一共有20类POI）；
         3）将这20个POi特征和道路的2维属性信息进行拼接，便可得到每个道路22维度的spatial_features了，这部分操作完成后便可以得到edges_data.h5这个文件。

**Comment by yule-BUAA** [comment]
您好，
由于POI数据是公司提供的，所以不便将关于POI的空间特征相关的处理代码公开。我在这里描述下提取spatial_features的流程：
1）对于路网结构信息，我们提供的预处理代码process_beijing_road_net.py可以生成beijing_roadnet.gpickle，该文件中的节点为每条道路，边为道路之间的连接关系，同时也包含了道路的2维属性信息（道路长度、道路包含的点数量）；
2）对于POI信息，我们提取了每条道路周围的各类型POI的数量（在使用的数据中，一共有20类POI）；
3）将这20个POi特征和道路的2维属性信息进行拼接，便可得到每个道路22维度的spatial_features了，这便是edges_data.h5这个文件所包含的内容。

**Comment by HaozheZhao** [comment]
> 您好， 由于POI数据是公司提供的，所以不便将关于POI的空间特征相关的处理代码公开。我在这里描述下提取spatial_features的流程： 1）对于路网结构信息，我们提供的预处理代码process_beijing_road_net.py可以生成beijing_roadnet.gpickle，该文件中的节点为每条道路，边为道路之间的连接关系，同时也包含了道路的2维属性信息（道路长度、道路包含的点数量）； 2）对于POI信息，我们提取了每条道路周围的各类型POI的数量（在使用的数据中，一共有20类POI）； 3）将这20个POi特征和道路的2维属性信息进行拼接，便可得到每个道路22维度的spatial_features了，这便是edges_data.h5这个文件所包含的内容。

您好，十分感谢您的回复，我还有如下两个问题想要询问一下：
1. 根据您的回复我能否作出以下的理解：spatial_features中有关poi的部分，是你们根据每条道路的POI情况进行了统计，计算了这20类POI的数量作为20维度的一个特征，然后和道路长度和包含的点数量构建了spatial_features。
2. 你们在处理数据时，对地区分割成了多个grid，想问一下此处分割的依据和意义是什么？
谢谢！

**Comment by yule-BUAA** [comment]
> 

1）你理解是正确的。这个每条道路“周围”的POI的实现是我们选取了每条道路0.002经纬度以内的POI，也就是大约222m，然后统计20类POI的数量。论文里也有详细的描述。
2）划分多个grid是因为在提取各个道路的流速特征时，由于出租车的数据量太大，所以为每个道路遍历一次所有的出租车数据是不可行的。因此，我们是将研究区域划分成了0.002经度*0.002纬度的网格，然后遍历一遍出租车数据，将每个出租车数据放置到其所在的网格中，再计算每个网格的平均速度。之后把每个道路所在的网格速度直接作为道路的流速特征。所以，划分grid只是在计算流速特征的时候用到了，我们的模型还是处理的是graph形式的路网结构，并使用图卷积考虑空间影响。
