### ISSUE TITLE
DSTGCN中子图的特征提取是怎么做的？

### ISSUE THREAD

**Issue by HaozheZhao** [yule-BUAA/DSTGCN#6]
我想询问一下，在DSTGCN中，我看代码中使用了如下方式来提取GCN后的时空特征：
```
for num_nodes in nums_nodes:

            s_features.append(s_out[id])

            t_features.append(t_out[id])

            id += num_nodes
```
我观察是将一个batch中的子图的最后一个节点的时空特征作为子图的时空特征？这样的合理性是什么呢？

**Comment by yule-BUAA** [comment]
你好，代码中的每张子图是以每个正/负样本为中心并结合其k阶邻居构建的，且保证了**该样本为对应的子图的第一个节点**，https://github.com/yule-BUAA/DSTGCN/blob/5d04a93981f8489ad462982bac3172f833c7c787/utils/data_container.py#L120。

由于我们要预测的是每张子图的**中心节点**（也就是我们的目标样本）发生交通事故的概率，因此，我们只需要取出一个batch中的各个子图的**第一个节点**时空卷积后的时空特征即可完成预测。
