### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by yesihati0719** [yule-BUAA/DSTGCN#8]
请问一下，如果数据没有经纬度，怎么解决呢？可不可以不用经纬度？

**Comment by yule-BUAA** [comment]
如果没有经纬度的话，就没办法获取和空间信息相关的输入了，例如空间图结构，路网特征以及POI特征等。如果你的数据中对于每个accident都有对应的上述各类特征，是可以使用的；如果没有对应的特征，那么还是需要经纬度的信息。

**Comment by yesihati0719** [comment]
我有高速公路的具体桩号和方向，事故数据可以对应具体的桩号和方向，这个可以做经纬度吗？

**Comment by yule-BUAA** [comment]
首先需要明确的是经纬度的作用是提取空间信息，尤其是**路网结构**。
在你的数据中，已经完成了事故数据和路段的匹配，如果你还可以根据公路的桩号和方向来得到**路网结构**（即路段之间的相连关系和路段之间的距离），那么你就可以得到一个graph，这样是可以使用这篇工作的模型的。至于上面我说的路网特征和POI特征，如果没有就不作为输入的feature，也是可以的。重点还是**路网结构**是否可以获取到。
